### ISSUE TITLE
Plugin uses wrong path for per-file pep8 xml-reports

### ISSUE THREAD

**Issue by vglushonkov** [jenkinsci/violations-plugin#36]
Working on Windows
Launching pep8 check, it successfully creates XML report, but violations plugin roports error. It seems it uses absolute path somewhere instaed of relative. Please, at least help me to find a direction to look (i downloada the plugin src and trying to find to fix it):

 generated xml file: C:\Jenkins\jobs\python-template-2\workspace\reports\pep8.xml 
=============== 91 failed, 33 skipped, 1 error in 1.52 seconds ================

C:\Jenkins\jobs\python-template-2\workspace>exit 1 
Build step 'Выполнить команду Windows' marked build as failure
ERROR: Publisher hudson.plugins.violations.ViolationsPublisher aborted due to exception
java.io.FileNotFoundException: C:\Jenkins\jobs\python-template-2\builds\2013-10-23_20-03-27\violations\file\C:\Jenkins\jobs\python-template-2\workspace\utilities\capable\admin.py.xml (Syntax error in filename or path)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at hudson.FilePath.write(FilePath.java:1642)
    at hudson.plugins.violations.generate.ExecuteFilePath.execute(ExecuteFilePath.java:42)
    at hudson.plugins.violations.generate.GenerateXML.execute(GenerateXML.java:47)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:122)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:25)
    at hudson.FilePath.act(FilePath.java:912)
    at hudson.FilePath.act(FilePath.java:885)
    at hudson.plugins.violations.ViolationsPublisher.perform(ViolationsPublisher.java:74)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:781)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:753)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:706)
    at hudson.model.Run.execute(Run.java:1690)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:230)
Finished: FAILURE

**Comment by tomasbjerre** [comment]
@iamexe Is this still an issue or can it be closed?

**Comment by Tryph** [comment]
It is still an issue:

```
C:\dev\compil_environment\jenkins_workspace\collaboar\tests\musketeer\quality\pep8.txt
ERROR: Step ‘Report Violations’ aborted due to exception: 
java.io.FileNotFoundException: C:\Program Files (x86)\Jenkins\jobs\musketeer_quality\builds\9\violations\file\C:\dev\compil_environment\jenkins_workspace\collaboar\src\launch_boar_utils.py.xml (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at hudson.FilePath.write(FilePath.java:1879)
    at hudson.plugins.violations.generate.ExecuteFilePath.execute(ExecuteFilePath.java:40)
    at hudson.plugins.violations.generate.GenerateXML.execute(GenerateXML.java:47)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:122)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:25)
    at hudson.FilePath.act(FilePath.java:990)
    at hudson.FilePath.act(FilePath.java:968)
    at hudson.plugins.violations.ViolationsPublisher.perform(ViolationsPublisher.java:74)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

Jenkins 1.651.3
Violations 0.7.11
