### ISSUE TITLE
File not found exception during publishing 

### ISSUE THREAD

**Issue by WilliamBerryiii** [jenkinsci/violations-plugin#47]
I am receiving a file not found exception when reports are being published.  Please see stack trace below:

Build step 'Execute a set of scripts' changed build result to FAILURE
Build step 'Execute a set of scripts' marked build as failure
ERROR: Publisher hudson.plugins.violations.ViolationsPublisher aborted due to exception
java.io.FileNotFoundException: D:{build_root}{project_name}\2014-04-01_15-06-43\violations\file{source_file_namesapce}+<Delete>d__19.xml (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at hudson.FilePath.write(FilePath.java:1683)
    at hudson.plugins.violations.generate.ExecuteFilePath.execute(ExecuteFilePath.java:40)
    at hudson.plugins.violations.generate.GenerateXML.execute(GenerateXML.java:47)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:122)
    at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:25)
    at hudson.FilePath.act(FilePath.java:914)
    at hudson.FilePath.act(FilePath.java:887)
    at hudson.plugins.violations.ViolationsPublisher.perform(ViolationsPublisher.java:74)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:742)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:714)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:663)
    at hudson.model.Run.execute(Run.java:1713)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:231)
Finished: FAILURE

**Comment by astrojuanlu** [comment]
Confirmed that the problem is with the paths. They must be relative to the root of the workspace.

**Comment by harlam357** [comment]
I'm seeing the exact same stack trace when attempting to publish violations reported by FxCop 14.0.

21:30:52 ERROR: Step ‘Report Violations’ aborted due to exception: 
21:30:52 java.io.FileNotFoundException: C:\{build_root}\{job_folder}\builds\29\violations\file\{project_namespace}+<>c__DisplayClass16_0.xml (The filename, directory name, or volume label syntax is incorrect)
21:30:52 	at java.io.FileOutputStream.open0(Native Method)
21:30:52 	at java.io.FileOutputStream.open(Unknown Source)
21:30:52 	at java.io.FileOutputStream.<init>(Unknown Source)
21:30:52 	at java.io.FileOutputStream.<init>(Unknown Source)
21:30:52 	at hudson.FilePath.write(FilePath.java:1879)
21:30:52 	at hudson.plugins.violations.generate.ExecuteFilePath.execute(ExecuteFilePath.java:40)
21:30:52 	at hudson.plugins.violations.generate.GenerateXML.execute(GenerateXML.java:47)
21:30:52 	at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:122)
21:30:52 	at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:25)
21:30:52 	at hudson.FilePath.act(FilePath.java:996)
21:30:52 	at hudson.FilePath.act(FilePath.java:974)
21:30:52 	at hudson.plugins.violations.ViolationsPublisher.perform(ViolationsPublisher.java:74)
21:30:52 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
21:30:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
21:30:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
21:30:52 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
21:30:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
21:30:52 	at hudson.model.Run.execute(Run.java:1753)
21:30:52 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
21:30:52 	at hudson.model.ResourceController.execute(ResourceController.java:98)
21:30:52 	at hudson.model.Executor.run(Executor.java:404)

**Comment by antibarbie** [comment]
Same problem with FxCop ...
It makes me wonder if the violations plugin is in need of some maintenance ?
It seems it has not been updated since 2012.

Maybe the violations plugin should alter the names, to create valid file names.

```
ERROR: Step ‘Report Violations’ aborted due to exception: 
java.io.FileNotFoundException: C:\JOBS\xxxx-Dev-x64\builds\2616\violations\file\msclr.interop.context_node<wchar_t const *,System::String ^>.xml (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at hudson.FilePath.write(FilePath.java:1879)
	at hudson.plugins.violations.generate.ExecuteFilePath.execute(ExecuteFilePath.java:40)
	at hudson.plugins.violations.generate.GenerateXML.execute(GenerateXML.java:47)
	at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:122)
	at hudson.plugins.violations.ViolationsCollector.invoke(ViolationsCollector.java:25)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at hudson.plugins.violations.ViolationsPublisher.perform(ViolationsPublisher.java:74)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by antibarbie** [comment]
Hmmm it seems to be fixed in the last pre-release, not available in the plugin manager, only manually.

https://github.com/jenkinsci/violations-plugin/releases

**Comment by WilliamBerryiii** [comment]
This issue has been open for years with no progress - I'm closing it.
